services:
  client:
    container_name: client
    restart: always
    build: ./fullstack/client
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    container_name: api
    restart: always
    build: ./fullstack/api
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - 27017
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
